"""create menu and role table

Revision ID: 21983d824074
Revises: 
Create Date: 2024-12-02 16:29:27.204487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21983d824074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='parent id'),
    sa.Column('menu_name', sa.String(length=20), nullable=False, comment='菜单名'),
    sa.Column('path', sa.String(length=30), nullable=False, comment='访问路径'),
    sa.Column('sort', sa.String(length=30), nullable=False, comment='排序'),
    sa.Column('menu_type', sa.Integer(), nullable=False, comment='0=目录,1=菜单,2=按钮'),
    sa.Column('icon', sa.String(length=30), nullable=False, comment='图标'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('create_user', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=False, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='0=正常,1=已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('sort', sa.String(length=30), nullable=False, comment='排序'),
    sa.Column('role_name', sa.String(length=30), nullable=False, comment='角色名'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0=正常,1=禁止'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('create_user', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=False, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='0=正常,1=已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=20), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('create_user', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=False, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='0=正常,1=已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('create_user', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=False, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='0=正常,1=已删除'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_menu')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('menus')
    # ### end Alembic commands ###
