"""add users model

Revision ID: 36f98288f7f5
Revises: 0a149d7cd06f
Create Date: 2024-11-20 14:24:19.381873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f98288f7f5'
down_revision: Union[str, None] = '0a149d7cd06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户姓名'),
    sa.Column('password', sa.String(length=20), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='电子邮箱'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_user', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_user', sa.Integer(), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), nullable=True, comment='删除标识：0-正常 1-已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
